# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Supports turnkey widgets

Parameters:
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailWebappDomain:
    Type: String
    Description: The domain of the Lightrail web app
    AllowedPattern: (\w+\.)+\w{3}
  SecureConfigBucket:
    Type: String
    Description: Name of the S3 bucket holding the JWT secure config
  SecureConfigKeyJwt:
    Type: String
    Description: Key of the JWT secure config object in S3
  SecureConfigKeyRoleDefinitions:
    Type: String
    Description: Key of the role definitions secure config object in S3
  SecureConfigKeyStripe:
    Type: String
    Description: Key of the Stripe Connect secure config object in S3
  SecureConfigKmsArn:
    Type: String
    Description: Optional ARN of the KMS encrypting the S3 bucket
    AllowedPattern: arn:aws:kms:[a-zA-Z_0-9\-]+:\d{12}:key/[a-zA-Z_0-9+=,.@\-_/]+

Resources:
  StripeConnectStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: ShortName
          Value: StripeConnectStateTable
        - Key: Service
          Value: Turnkey

  GiftcardPurchaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/giftcardPurchase/giftcardPurchase.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Environment:
        Variables:
          LIGHTRAIL_DOMAIN: !Ref LightrailDomain
          SECURE_CONFIG_BUCKET: !Ref SecureConfigBucket
          SECURE_CONFIG_KEY_JWT: !Ref SecureConfigKeyJwt
          SECURE_CONFIG_KEY_ROLE_DEFINITIONS: !Ref SecureConfigKeyRoleDefinitions
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/${SecureConfigKeyJwt}"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/${SecureConfigKeyRoleDefinitions}"
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - !Ref SecureConfigKmsArn
              Condition:
                StringLike:
                  "kms:ViaService":
                    !Sub "s3.${AWS::Region}.amazonaws.com"
                  "kms:EncryptionContext:aws:s3:arn":
                    !Sub "arn:aws:s3:::${SecureConfigBucket}/*"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
              #Condition:
              #  StringEquals:
              #   "ses:FromAddress":
              #      "email@example.com"
      Tags:
        ShortName: GiftcardPurchaseFunction
        Service: Turnkey
      Events:
        PurchaseGiftcard:
          Type: Api
          Properties:
            Path: /v1/turnkey/purchaseGiftcard
            Method: ANY

  StripeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/stripe/stripe.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Environment:
        Variables:
          LIGHTRAIL_DOMAIN: !Ref LightrailDomain
          LIGHTRAIL_WEBAPP_DOMAIN: !Ref LightrailWebappDomain
          SECURE_CONFIG_BUCKET: !Ref SecureConfigBucket
          SECURE_CONFIG_KEY_JWT: !Ref SecureConfigKeyJwt
          SECURE_CONFIG_KEY_ROLE_DEFINITIONS: !Ref SecureConfigKeyRoleDefinitions
          SECURE_CONFIG_KEY_STRIPE: !Ref SecureConfigKeyStripe
          STRIPE_CONNECT_STATE_TABLE: !Ref StripeConnectStateTable
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${StripeConnectStateTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${StripeConnectStateTable}/*"
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/${SecureConfigKeyJwt}"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/${SecureConfigKeyRoleDefinitions}"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/${SecureConfigKeyStripe}"
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - !Ref SecureConfigKmsArn
              Condition:
                StringLike:
                  "kms:ViaService":
                    !Sub "s3.${AWS::Region}.amazonaws.com"
                  "kms:EncryptionContext:aws:s3:arn":
                    !Sub "arn:aws:s3:::${SecureConfigBucket}/*"
      Tags:
        ShortName: StripeFunction
        Service: Turnkey
      Events:
        Rest:
          Type: Api
          Properties:
            Path: /v1/turnkey/{proxy+}
            Method: ANY
